import type { Metadata } from "next";
import "./globals.css";
import { headingFont, bodyFont } from "./fonts";
import { Providers } from "@/providers/Providers";
import { TrainingProvider } from "@/context/TrainingContext";
import { CartProvider } from "@/context/CartContext";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import WhatsAppButton from "@/components/WhatsAppButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bodyFont.variable} ${headingFont.variable} ${bodyFont.className} antialiased`}
      >
        <Providers>
          <TrainingProvider>
            <CartProvider>
              <Navbar />  
              <main className="pt-14 sm:pt-16 md:pt-20 lg:pt-24 xl:pt-52 bg-[#F6F4F1] min-h-screen">
                {children}
              </main>
              <Footer />
              <WhatsAppButton />
            </CartProvider>
          </TrainingProvider>
        </Providers>
      </body>
    </html>
  );
}
